[package]
name = 'SatayTortugaAriesLLSStrategy'
version = '1.0.0'

[addresses]
tortuga_aries_lls_strategy = "0x895cff28180ccdd3746a22a5e8ff929060d4ae58510a97662d90339100ed75c7"

[dependencies.SatayAriesBlocks]
git = "https://github.com/satay-protocol/satay-blocks"
rev = "master"
subdir = "aries-blocks"

[dependencies.TortugaGovernance]
git = "https://github.com/satay-protocol/partner-interfaces"
rev = "mainnet"
subdir = "tortuga/tortuga-governance"


