[package]
name = 'SatayTortugaAriesLLSStrategy'
version = '1.0.0'

[addresses]
tortuga_aries_lls_strategy = "0xe3eaddfcc4d7436d26fef92ee39685ef176e3513dc736d116129ce055c07afac"

[dependencies.SatayAriesBlocks]
git = "https://github.com/satay-protocol/satay-blocks"
rev = "master"
subdir = "aries-blocks"

[dependencies.TortugaGovernance]
git = "https://github.com/satay-protocol/partner-interfaces"
rev = "mainnet"
subdir = "tortuga/tortuga-governance"


