[package]
name = 'SatayTortugaAriesLLSVaultAdapter'
version = '1.0.0'

[addresses]
satay_tortuga_aries_lls = "0xe3eaddfcc4d7436d26fef92ee39685ef176e3513dc736d116129ce055c07afac"

[dependencies.satay]
git = "https://github.com/satay-protocol/satay-aptos"
rev = "main"

[dependencies.SatayTortugaAriesLLSStrategy]
local = "../strategy"


